<!-- [BEGIN] Page Header -->
<div style='margin:0px;padding:20px;height:74px;
	background:#000000 url(images/top.png);color:#ffffff;'>

	<div style='font-size:200%;'>
Contact Us	</div>

	<div style='margin-top:5px;'>
	<span style='font-size:10px;'>
		Generated by <a href='http://www.phpkobo.com/form2db-builder' style='text-decoration:none;' target='_blank'>
		<span style='font-weight:bold;color:#fffff0;'>
Form2DB Builder</span></a>
v1.30 on
		<span style='font-weight:bold;'>2013-09-24 16:01:39</span>,
	</span> 

	<span style='font-size:10px;'>
		Base Code : <a href='http://www.phpkobo.com/form2db.php' style='text-decoration:none;' target='_blank'>
		<span style='font-weight:bold;color:#fffff0;'>Form2DB</span></a>
v1.14	</span>
	</div>

</div>
<!-- [END] Page Header -->
